Add files via upload

diff --git a/.github/workflows/add-ssh-key.yml b/.github/workflows/add-ssh-key.yml
--- a/.github/workflows/add-ssh-key.yml
+++ b/.github/workflows/add-ssh-key.yml
@@ -10,14 +10,16 @@ jobs:
     steps:
       - name: Setup SSH
         run: |
+          test -n "${{ secrets.SSH_PRIVATE_KEY }}" || (echo "Missing SSH_PRIVATE_KEY" && exit 1)
+          test -n "${{ secrets.SERVER_HOST }}" || (echo "Missing SERVER_HOST" && exit 1)
+          test -n "${{ secrets.SERVER_USER }}" || (echo "Missing SERVER_USER" && exit 1)
           mkdir -p ~/.ssh
           echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
-          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
 
       - name: Add public key to server
         run: |
-          ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
+          ssh -o StrictHostKeyChecking=accept-new -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
             mkdir -p ~/.ssh
             grep -qxF 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9JRy9wrAEG/+m6FvTEK4tdeNpGtKpEVJLS/C9JHfJE openstack-rescue' ~/.ssh/authorized_keys || echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9JRy9wrAEG/+m6FvTEK4tdeNpGtKpEVJLS/C9JHfJE openstack-rescue' >> ~/.ssh/authorized_keys
             chmod 700 ~/.ssh
